language: go

env:
  - GO111MODULE=on

git:
  depth: 1

install:
  - "go get github.com/mattn/goveralls"

script:
  - go test -v -race ./...
  - COVERALLS_TOKEN=5TCfaWdApdJpouGNqmQm7HRhttWXyDH2D $GOPATH/bin/goveralls -service=travis-ci
  - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o sitemap cmd/sitemap/main.go